import React, { useEffect } from "react";
import NavBar from "./NavBar";

const Youtube = () => {
  useEffect(() => {
    const handleScroll = () => {
      const parallaxElements = document.querySelectorAll(".parallax");
      for (let element of parallaxElements) {
        const scrollPosition = window.pageYOffset;
        const elementPosition = element.offsetTop;
        const distance = scrollPosition - elementPosition;
        element.style.transform = `translateY(${distance * 0.5}px)`;
      }
    };

    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  const fallochImage = {
    backgroundImage:
      "url('https://coorieprojectimagesbbbbblddddd.s3.eu-west-2.amazonaws.com/falloch.jpg')",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    height: "1400px",
  };

  const containerStyle = {
    overflow: "hidden",
  };

  return (
    <>
      <div>
        <section>
          <div
            className="relative h-screen bg-cover"
            style={{ ...fallochImage, ...containerStyle }}
          >
            <NavBar className="absolute top-0 left-0 right-0" />
            <h3
              className="text-5xl text-white text-center pl-96 pr-96 py-60 parallax"
              style={{ textShadow: "0 0 1px black" }}
            >
              All profits generated by the advertising revenue garnered from the
              Coorie Project Channel will be donated to climate change research
              charities or invested back into other climate change focused
              sustainability projects/exhibitions.
              <br />
              <br />
              Anyone concerned about and wanting to help tackle climate change
              need only like, subscribe and watch. Funds can be generated from
              clicks and views, rather than donations.
            </h3>
          </div>
        </section>

        <div style={{ position: "relative", paddingTop: "56.25%", height: 0 }}>
          <iframe
            className="mx-auto"
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              width: "100%",
              height: "100%",
              padding: "10%",
            }}
            src="https://www.youtube.com/embed/weIMOdI1OAk"
            title="YouTube video player"
            frameBorder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            allowFullScreen
          ></iframe>
        </div>
      </div>
      <div className="flex flex-col justify-center items-center py-5">
      <a
        href="https://www.youtube.com/channel/UCULPVxk5Zjk2zje5drAou_Q?app=desktop&disable_polymer=true"
        target="_blank"
        rel="noopener noreferrer"
        className="text-5xl font-light italic relative inline-block px-4 py-2 font-medium group"
      >
        <span className="absolute inset-0 w-full h-full transition duration-200 ease-out transform translate-x-1 translate-y-1 bg-black group-hover:-translate-x-0 group-hover:-translate-y-0"></span>
        <span className="absolute inset-0 w-full h-full bg-white border-2 border-black group-hover:bg-black"></span>
        <span className="relative text-black group-hover:text-white">
          Subscribe to Channel
        </span>
      </a>
    </div>
    </>
  );
};

export default Youtube;
